"""empty message

Revision ID: 22617912fc7e
Revises: 74bbfa149f30
Create Date: 2022-03-29 00:19:51.672607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "22617912fc7e"
down_revision = "74bbfa149f30"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invokation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fold_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=80), nullable=False),
        sa.Column("state", sa.String(length=80), nullable=True),
        sa.Column("log", sa.Text(), nullable=True),
        sa.Column("timedelta", sa.Interval(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fold_id"], ["roles.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("invokation")
    # ### end Alembic commands ###
