"""empty message

Revision ID: 40cf3787d6b4
Revises: 01db8a1f2304
Create Date: 2021-09-29 20:22:27.361444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "40cf3787d6b4"
down_revision = "01db8a1f2304"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "roles", sa.Column("job_id_features", sa.String(length=80), nullable=True)
    )
    op.add_column(
        "roles", sa.Column("state_features", sa.String(length=80), nullable=True)
    )
    op.add_column(
        "roles", sa.Column("job_id_models", sa.String(length=80), nullable=True)
    )
    op.add_column(
        "roles", sa.Column("state_models", sa.String(length=80), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("roles", "state_models")
    op.drop_column("roles", "job_id_models")
    op.drop_column("roles", "state_features")
    op.drop_column("roles", "job_id_features")
    # ### end Alembic commands ###
