"""empty message

Revision ID: 64b92ebec814
Revises: ae02662591d7
Create Date: 2023-10-31 18:56:06.251027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b92ebec814'
down_revision = 'ae02662591d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docking', sa.Column('pose_confidences', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('docking', 'pose_confidences')
    # ### end Alembic commands ###
