"""empty message

Revision ID: 67cbca5ca8d2
Revises: fb234927791b
Create Date: 2023-04-19 04:38:24.866094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67cbca5ca8d2'
down_revision = 'fb234927791b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'public')
    # ### end Alembic commands ###
