"""empty message

Revision ID: 6c4d9d4a8de3
Revises: 67cbca5ca8d2
Create Date: 2023-04-24 02:41:26.734344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4d9d4a8de3'
down_revision = '67cbca5ca8d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docking', sa.Column('tool', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('docking', 'tool')
    # ### end Alembic commands ###
