"""empty message

Revision ID: 74bbfa149f30
Revises: 226b6501021e
Create Date: 2022-01-10 21:59:18.518785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74bbfa149f30'
down_revision = '226b6501021e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('use_af2', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('af2_model_preset', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'af2_model_preset')
    op.drop_column('roles', 'use_af2')
    # ### end Alembic commands ###
