"""empty message

Revision ID: f4a46c77621f
Revises: 97f6e102bccf
Create Date: 2023-08-04 17:10:26.759210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a46c77621f'
down_revision = '97f6e102bccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_type', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access_type')
    # ### end Alembic commands ###
