"""empty message

Revision ID: fb234927791b
Revises: 528cdc2a9517
Create Date: 2022-10-12 18:33:13.421047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fb234927791b"
down_revision = "528cdc2a9517"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "docking", sa.Column("bounding_box_residue", sa.String(), nullable=True)
    )
    op.add_column(
        "docking", sa.Column("bounding_box_radius_angstrom", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("docking", "bounding_box_radius_angstrom")
    op.drop_column("docking", "bounding_box_residue")
    # ### end Alembic commands ###
