"""empty message

Revision ID: 207d981c5c68
Revises: 657a794d507a
Create Date: 2025-01-07 18:26:56.363484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207d981c5c68'
down_revision = '657a794d507a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fold_id', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('extra_seq_ids', sa.String(), nullable=True),
    sa.Column('dms_starting_seq_ids', sa.String(), nullable=True),
    sa.Column('invokation_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fold_id'], ['roles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invokation_id'], ['invokation.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embeddings')
    # ### end Alembic commands ###
