"""empty message

Revision ID: 830dfa6e0eae
Revises: 0b1cb6039d5f
Create Date: 2025-01-22 22:27:59.162225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830dfa6e0eae'
down_revision = '0b1cb6039d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yaml_config', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('yaml_config')

    # ### end Alembic commands ###
