"""empty message

Revision ID: 8b3934db5c08
Revises: f43cf56e1cb4
Create Date: 2025-02-13 19:49:57.777515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b3934db5c08'
down_revision = 'f43cf56e1cb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index('ix_roles_public', ['public'], unique=False)
        batch_op.create_index('ix_roles_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_roles_yaml_config', ['yaml_config'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('ix_roles_yaml_config')
        batch_op.drop_index('ix_roles_user_id')
        batch_op.drop_index('ix_roles_public')

    # ### end Alembic commands ###
