"""empty message

Revision ID: 95d0e6ec9b80
Revises: b96b3cf3696e
Create Date: 2021-09-27 22:07:50.120068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "95d0e6ec9b80"
down_revision = "b96b3cf3696e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("roles", sa.Column("stdout", sa.Text(), nullable=True))
    op.alter_column(
        "roles", "failed_error_message", nullable=True, new_column_name="stderr"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("roles", "stdout")
    op.alter_column(
        "roles", "stderr", nullable=True, new_column_name="failed_error_message"
    )
    # ### end Alembic commands ###
