"""empty message

Revision ID: ae02662591d7
Revises: f4a46c77621f
Create Date: 2023-09-13 23:17:38.925357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae02662591d7'
down_revision = 'f4a46c77621f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invokation', sa.Column('command', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invokation', 'command')
    # ### end Alembic commands ###
