"""empty message

Revision ID: b3b0c497c89a
Revises: 7019b900d3ce
Create Date: 2025-02-20 21:23:34.759781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b0c497c89a'
down_revision = '7019b900d3ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fold_evolution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('finetuning_model_checkpoint', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fold_evolution', schema=None) as batch_op:
        batch_op.drop_column('finetuning_model_checkpoint')
        batch_op.drop_column('mode')

    # ### end Alembic commands ###
