"""empty message

Revision ID: 10c828641680
Revises: b84be04f23ad
Create Date: 2025-07-30 20:28:52.849146

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "10c828641680"
down_revision = "b84be04f23ad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("campaign_rounds", schema=None) as batch_op:
        batch_op.add_column(sa.Column("result_activity_fpath", sa.Text(), nullable=True))
        batch_op.drop_column("input_activity_fpath")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("campaign_rounds", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("input_activity_fpath", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.drop_column("result_activity_fpath")

    # ### end Alembic commands ###
