"""empty message

Revision ID: 1fe75c941782
Revises: 367b4b9359e3
Create Date: 2025-08-04 18:00:46.457633

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1fe75c941782"
down_revision = "367b4b9359e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.add_column(sa.Column("domain_boundaries", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.drop_column("domain_boundaries")

    # ### end Alembic commands ###
