"""empty message

Revision ID: 226b6501021e
Revises: d14393b6e2a3
Create Date: 2021-12-15 20:21:31.159126

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "226b6501021e"
down_revision = "d14393b6e2a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("roles", sa.Column("features_timedelta", sa.Interval(), nullable=True))
    op.add_column("roles", sa.Column("models_timedelta", sa.Interval(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("roles", "models_timedelta")
    op.drop_column("roles", "features_timedelta")
    # ### end Alembic commands ###
