"""empty message

Revision ID: 2428371a122b
Revises: c5de6f97d456
Create Date: 2022-09-26 22:34:58.214839

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2428371a122b"
down_revision = "c5de6f97d456"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("roles", "msa_size_gb")
    op.drop_column("roles", "num_homooligomers")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "roles",
        sa.Column("num_homooligomers", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "roles",
        sa.Column(
            "msa_size_gb",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
