"""empty message

Revision ID: 367b4b9359e3
Revises: f0a8c61a233a
Create Date: 2025-08-01 19:17:01.318907

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "367b4b9359e3"
down_revision = "f0a8c61a233a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("embeddings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("domain_boundaries", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("embeddings", schema=None) as batch_op:
        batch_op.drop_column("domain_boundaries")

    # ### end Alembic commands ###
