"""empty message

Revision ID: 451e692de9bd
Revises: 830dfa6e0eae
Create Date: 2025-01-28 23:33:05.946771

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "451e692de9bd"
down_revision = "830dfa6e0eae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "logits",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("fold_id", sa.Integer(), nullable=True),
        sa.Column("logit_model", sa.String(), nullable=False),
        sa.Column("invokation_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["fold_id"], ["roles.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["invokation_id"], ["invokation.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("logits")
    # ### end Alembic commands ###
