"""empty message

Revision ID: 49be64d29de6
Revises: 787b99c1b4c8
Create Date: 2025-07-29 16:11:09.817081

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "49be64d29de6"
down_revision = "787b99c1b4c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.add_column(sa.Column("naturalness_model", sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column("embedding_model", sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.drop_column("embedding_model")
        batch_op.drop_column("naturalness_model")

    # ### end Alembic commands ###
