"""empty message

Revision ID: 528cdc2a9517
Revises: 2428371a122b
Create Date: 2022-09-26 23:52:14.820574

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "528cdc2a9517"
down_revision = "2428371a122b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("roles", sa.Column("disable_relaxation", sa.Boolean(), nullable=True))
    op.drop_column("roles", "use_af2")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("roles", sa.Column("use_af2", sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column("roles", "disable_relaxation")
    # ### end Alembic commands ###
