"""empty message

Revision ID: 634d0d8e8eb0
Revises: b3b0c497c89a
Create Date: 2025-03-07 22:16:06.990337

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "634d0d8e8eb0"
down_revision = "b3b0c497c89a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("invokation", schema=None) as batch_op:
        batch_op.alter_column(
            "starttime",
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )

    with op.batch_alter_table("logits", schema=None) as batch_op:
        batch_op.add_column(sa.Column("get_depth_two_logits", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("logits", schema=None) as batch_op:
        batch_op.drop_column("get_depth_two_logits")

    with op.batch_alter_table("invokation", schema=None) as batch_op:
        batch_op.alter_column(
            "starttime",
            existing_type=sa.DateTime(timezone=True),
            type_=postgresql.TIMESTAMP(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
