"""empty message

Revision ID: 657a794d507a
Revises: 9d7d8c2df487
Create Date: 2025-01-06 00:02:55.562722

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "657a794d507a"
down_revision = "9d7d8c2df487"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fold_evolution", schema=None) as batch_op:
        batch_op.add_column(sa.Column("embedding_files", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("invokation_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            None,
            "invokation",
            ["invokation_id"],
            ["id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fold_evolution", schema=None) as batch_op:
        # TODO(jbr): drop_constraint expects string constraint_name, not None
        batch_op.drop_constraint(None, type_="foreignkey")  # pyright: ignore[reportArgumentType]
        batch_op.drop_column("invokation_id")
        batch_op.drop_column("embedding_files")

    # ### end Alembic commands ###
