"""empty message

Revision ID: 7019b900d3ce
Revises: 8b3934db5c08
Create Date: 2025-02-14 19:08:51.925097

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7019b900d3ce"
down_revision = "8b3934db5c08"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("diffusion_samples", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.drop_column("diffusion_samples")

    # ### end Alembic commands ###
