"""empty message

Revision ID: 716f0e76db5e
Revises: 860c11aa34b6
Create Date: 2025-06-03 22:38:40.132785

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "716f0e76db5e"
down_revision = "860c11aa34b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("teselagen_api_key", sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("teselagen_api_key")

    # ### end Alembic commands ###
