"""empty message

Revision ID: 736364a7a69b
Revises: a04d68cd036b
Create Date: 2025-07-30 22:42:32.700457

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "736364a7a69b"
down_revision = "a04d68cd036b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("campaign_rounds", schema=None) as batch_op:
        batch_op.add_column(sa.Column("input_templates", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("campaign_rounds", schema=None) as batch_op:
        batch_op.drop_column("input_templates")

    # ### end Alembic commands ###
