"""empty message

Revision ID: 787b99c1b4c8
Revises: f27de8df2d3e
Create Date: 2025-07-29 06:21:26.514915

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "787b99c1b4c8"
down_revision = "f27de8df2d3e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaigns",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("fold_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["fold_id"], ["roles.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "campaign_rounds",
        sa.Column("campaign_id", sa.Integer(), nullable=True),
        sa.Column("date_started", sa.DateTime(), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"], ["campaigns.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("campaign_rounds")
    op.drop_table("campaigns")
    # ### end Alembic commands ###
