"""empty message

Revision ID: 860c11aa34b6
Revises: 8c651a539c70
Create Date: 2025-05-26 00:04:56.279353

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "860c11aa34b6"
down_revision = "8c651a539c70"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fold_evolution", schema=None) as batch_op:
        batch_op.add_column(sa.Column("num_mutants", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fold_evolution", schema=None) as batch_op:
        batch_op.drop_column("num_mutants")

    # ### end Alembic commands ###
