"""empty message

Revision ID: 88c49e62b16c
Revises: 736364a7a69b
Create Date: 2025-08-01 06:14:08.755542

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "88c49e62b16c"
down_revision = "736364a7a69b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("campaign_rounds", schema=None) as batch_op:
        batch_op.add_column(sa.Column("few_shot_run_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            None,
            "fold_evolution",
            ["few_shot_run_id"],
            ["id"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("campaign_rounds", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")  # type: ignore[reportArgumentType]
        batch_op.drop_column("few_shot_run_id")

    # ### end Alembic commands ###
