"""empty message

Revision ID: 89755044bc1b
Revises: b52b4ecd979c
Create Date: 2025-07-30 03:17:56.569400

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "89755044bc1b"
down_revision = "b52b4ecd979c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("embeddings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("output_fpath", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("embeddings", schema=None) as batch_op:
        batch_op.drop_column("output_fpath")

    # ### end Alembic commands ###
