"""empty message

Revision ID: 8c651a539c70
Revises: a1c0747312d3
Create Date: 2025-04-30 06:01:19.909895

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8c651a539c70"
down_revision = "a1c0747312d3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fold_evolution", schema=None) as batch_op:
        batch_op.add_column(sa.Column("naturalness_files", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("few_shot_params", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fold_evolution", schema=None) as batch_op:
        batch_op.drop_column("few_shot_params")
        batch_op.drop_column("naturalness_files")

    # ### end Alembic commands ###
