"""empty message

Revision ID: 998e1302e4e5
Revises: 1fe75c941782
Create Date: 2025-08-18 18:25:10.315794

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "998e1302e4e5"
down_revision = "1fe75c941782"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("campaign_rounds", schema=None) as batch_op:
        batch_op.drop_column("promoted_templates")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("campaign_rounds", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "promoted_templates",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            )
        )

    # ### end Alembic commands ###
