"""empty message

Revision ID: 9d7d8c2df487
Revises: 64b92ebec814
Create Date: 2025-01-05 22:07:13.371442

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9d7d8c2df487"
down_revision = "64b92ebec814"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fold_evolution",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("fold_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["fold_id"], ["roles.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.alter_column(
            "tagstring",
            existing_type=sa.TEXT(),
            type_=sa.String(length=80),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.alter_column(
            "tagstring",
            existing_type=sa.String(length=80),
            type_=sa.TEXT(),
            existing_nullable=True,
        )

    op.drop_table("fold_evolution")
    # ### end Alembic commands ###
