"""empty message

Revision ID: a04d68cd036b
Revises: 10c828641680
Create Date: 2025-07-30 22:30:09.646964

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a04d68cd036b"
down_revision = "10c828641680"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("campaign_rounds", schema=None) as batch_op:
        batch_op.add_column(sa.Column("promoted_templates", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("campaign_rounds", schema=None) as batch_op:
        batch_op.drop_column("promoted_templates")

    # ### end Alembic commands ###
