"""empty message

Revision ID: a1c0747312d3
Revises: 634d0d8e8eb0
Create Date: 2025-04-11 03:48:33.315622

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a1c0747312d3"
down_revision = "634d0d8e8eb0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("embeddings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("extra_layers", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("embeddings", schema=None) as batch_op:
        batch_op.drop_column("extra_layers")

    # ### end Alembic commands ###
