"""Add mode and naturalness_run_id to CampaignRound

Revision ID: a7c47298c347
Revises: bef84aa71296
Create Date: 2025-07-30 17:28:14.758452

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a7c47298c347"
down_revision = "bef84aa71296"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("campaign_rounds", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mode", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("naturalness_run_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            None, "logits", ["naturalness_run_id"], ["id"], onupdate="CASCADE", ondelete="SET NULL"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("campaign_rounds", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")  # type: ignore[reportArgumentType]
        batch_op.drop_column("naturalness_run_id")
        batch_op.drop_column("mode")

    # ### end Alembic commands ###
