"""empty message

Revision ID: b52b4ecd979c
Revises: 49be64d29de6
Create Date: 2025-07-29 16:55:05.399664

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b52b4ecd979c"
down_revision = "49be64d29de6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fold_evolution", schema=None) as batch_op:
        batch_op.add_column(sa.Column("output_fpath", sa.String(), nullable=True))

    with op.batch_alter_table("logits", schema=None) as batch_op:
        batch_op.add_column(sa.Column("output_fpath", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("logits", schema=None) as batch_op:
        batch_op.drop_column("output_fpath")

    with op.batch_alter_table("fold_evolution", schema=None) as batch_op:
        batch_op.drop_column("output_fpath")

    # ### end Alembic commands ###
