"""empty message

Revision ID: b84be04f23ad
Revises: ef444aa3c92a
Create Date: 2025-07-30 19:54:17.843645

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b84be04f23ad"
down_revision = "ef444aa3c92a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("campaign_rounds", schema=None) as batch_op:
        batch_op.add_column(sa.Column("input_activity_fpath", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("campaign_rounds", schema=None) as batch_op:
        batch_op.drop_column("input_activity_fpath")

    # ### end Alembic commands ###
