"""empty message

Revision ID: b96b3cf3696e
Revises: d07af16977db
Create Date: 2021-09-23 22:07:50.120068

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b96b3cf3696e"
down_revision = "d07af16977db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("roles", sa.Column("failed_error_message", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("roles", "failed_error_message")
    # ### end Alembic commands ###
