"""empty message

Revision ID: bef84aa71296
Revises: 89755044bc1b
Create Date: 2025-07-30 03:35:06.747243

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bef84aa71296"
down_revision = "89755044bc1b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("embeddings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("date_created", sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table("fold_evolution", schema=None) as batch_op:
        batch_op.add_column(sa.Column("date_created", sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table("logits", schema=None) as batch_op:
        batch_op.add_column(sa.Column("date_created", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("logits", schema=None) as batch_op:
        batch_op.drop_column("date_created")

    with op.batch_alter_table("fold_evolution", schema=None) as batch_op:
        batch_op.drop_column("date_created")

    with op.batch_alter_table("embeddings", schema=None) as batch_op:
        batch_op.drop_column("date_created")

    # ### end Alembic commands ###
