"""empty message

Revision ID: c5de6f97d456
Revises: f39420cac7e9
Create Date: 2022-05-11 21:32:52.492920

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c5de6f97d456"
down_revision = "f39420cac7e9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "docking",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("ligand_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("ligand_smiles", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("receptor_fold_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("invokation_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("pose_energy", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["invokation_id"],
            ["invokation.id"],
            name="docking_invokation_id_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["receptor_fold_id"],
            ["roles.id"],
            name="docking_receptor_fold_id_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="docking_pkey"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("docking")
    # ### end Alembic commands ###
