"""empty message

Revision ID: d14393b6e2a3
Revises: 291e8e8dbab1
Create Date: 2021-12-01 02:46:33.778296

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d14393b6e2a3"
down_revision = "291e8e8dbab1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("roles", "stdout", nullable=True, new_column_name="features_log")
    op.alter_column("roles", "stderr", nullable=True, new_column_name="models_log")
    op.alter_column("roles", "job_id_features", nullable=True, new_column_name="features_job_id")
    op.alter_column("roles", "state_features", nullable=True, new_column_name="features_state")
    op.alter_column("roles", "job_id_models", nullable=True, new_column_name="models_job_id")
    op.alter_column("roles", "state_models", nullable=True, new_column_name="models_state")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("roles", "features_log", nullable=True, new_column_name="stdout")
    op.alter_column("roles", "models_log", nullable=True, new_column_name="stderr")
    op.alter_column("roles", "features_job_id", nullable=True, new_column_name="job_id_features")
    op.alter_column("roles", "features_state", nullable=True, new_column_name="state_features")
    op.alter_column("roles", "models_job_id", nullable=True, new_column_name="job_id_models")
    op.alter_column("roles", "models_state", nullable=True, new_column_name="state_models")
    # ### end Alembic commands ###
