"""Add slate_seq_ids to CampaignRound

Revision ID: ef444aa3c92a
Revises: a7c47298c347
Create Date: 2025-07-30 17:50:57.166383

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ef444aa3c92a"
down_revision = "a7c47298c347"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("campaign_rounds", schema=None) as batch_op:
        batch_op.add_column(sa.Column("slate_seq_ids", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("campaign_rounds", schema=None) as batch_op:
        batch_op.drop_column("slate_seq_ids")

    # ### end Alembic commands ###
