"""empty message

Revision ID: f0a8c61a233a
Revises: 88c49e62b16c
Create Date: 2025-08-01 17:30:52.920359

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f0a8c61a233a"
down_revision = "88c49e62b16c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fold_evolution", schema=None) as batch_op:
        batch_op.add_column(sa.Column("input_activity_fpath", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fold_evolution", schema=None) as batch_op:
        batch_op.drop_column("input_activity_fpath")

    # ### end Alembic commands ###
