"""empty message

Revision ID: f27de8df2d3e
Revises: eb3d56f4b77d
Create Date: 2025-07-20 05:10:14.536999

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f27de8df2d3e"
down_revision = "eb3d56f4b77d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("embeddings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("homolog_fasta", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("embeddings", schema=None) as batch_op:
        batch_op.drop_column("homolog_fasta")

    # ### end Alembic commands ###
