"""empty message

Revision ID: f39420cac7e9
Revises: 22617912fc7e
Create Date: 2022-04-19 18:32:41.849456

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f39420cac7e9"
down_revision = "22617912fc7e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("roles", sa.Column("create_date", sa.DateTime(), nullable=True))
    op.drop_column("roles", "models_log")
    op.drop_column("roles", "models_state")
    op.drop_column("roles", "features_log")
    op.drop_column("roles", "state")
    op.drop_column("roles", "models_job_id")
    op.drop_column("roles", "features_timedelta")
    op.drop_column("roles", "rq_job_id")
    op.drop_column("roles", "features_state")
    op.drop_column("roles", "models_timedelta")
    op.drop_column("roles", "features_job_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "roles",
        sa.Column("features_job_id", sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    )
    op.add_column(
        "roles",
        sa.Column(
            "models_timedelta",
            postgresql.INTERVAL(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "roles",
        sa.Column("features_state", sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    )
    op.add_column(
        "roles",
        sa.Column("rq_job_id", sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    )
    op.add_column(
        "roles",
        sa.Column(
            "features_timedelta",
            postgresql.INTERVAL(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "roles",
        sa.Column("models_job_id", sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    )
    op.add_column(
        "roles",
        sa.Column("state", sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    )
    op.add_column(
        "roles",
        sa.Column("features_log", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "roles",
        sa.Column("models_state", sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    )
    op.add_column("roles", sa.Column("models_log", sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column("roles", "create_date")
    # ### end Alembic commands ###
