"""empty message

Revision ID: f43cf56e1cb4
Revises: 451e692de9bd
Create Date: 2025-02-08 00:46:50.996530

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f43cf56e1cb4"
down_revision = "451e692de9bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("logits", schema=None) as batch_op:
        batch_op.add_column(sa.Column("use_structure", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("logits", schema=None) as batch_op:
        batch_op.drop_column("use_structure")

    # ### end Alembic commands ###
