version: "3.6"

services:
  frontend:
    build:
      context: frontend/
      target: build-stage
      args:
        - BACKEND_URL=http://localhost:8080
        - INSTITUTION=Local
        - HOST=0.0.0.0
    networks:
      - default
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./frontend/src:/app/src

  backend:
    build: backend/
    platform: linux/amd64
    depends_on:
      - db
      - redis
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - DEBUG=True
      - SECRET_KEY=superrandomandveryhardtoguessstring
      - OAUTH_REDIRECT_URI=http://localhost:8080/api/authorize
      - BACKEND_URL=http://localhost:8080
      - FRONTEND_URL=http://localhost:3000
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/postgres
      - RQ_REDIS_URL=redis://redis:6379/0
      - DISABLE_OAUTH_AUTHENTICATION=True
      - FOLDY_ADMIN_UPGRADE_LIST=tester@test.edu
      - FOLDY_STORAGE_TYPE=Local
      - FOLDY_LOCAL_STORAGE_DIR=/app/integration_tests/testdata
    networks:
      - default
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./backend/backend/app:/app/app
      - ./backend/backend/integration_tests:/app/integration_tests
      - ./backend/backend/migrations:/app/migrations
    restart: always
    entrypoint: python /app/main.py

  db:
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    image: postgres:15.6
    networks:
      - default
    ports:
      - 127.0.0.1:5432:5432
    restart: always

  redis:
    image: "redis:7.2-alpine"
    ports:
      - 127.0.0.1:6379:6379
